name: Build Package

on:
  create:
    tags:
      - '*'
jobs:    
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: dist/main
            asset_name: main-linux-amd64
            suffix: 
          - os: windows-latest
            artifact_name: dist/main.exe
            asset_name: main-windows-amd64
            suffix: .exe
          - os: macos-latest
            artifact_name: dist/main
            asset_name: main-macos-amd64
            suffix: 
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x            
    - name: info
      run: |
          echo ${{matrix.artifact_name}}
          echo ${{matrix.os}}
          echo ${{matrix.asset_name}}-${{env.GITHUB_REF_SLUG}}${{matrix.suffix}}
    - name: get dependencies
      run: |
          pip install readchar
          git clone https://github.com/pyinstaller/pyinstaller.git
          cd pyinstaller/bootloader
          python waf configure
          python waf all
          cd ..
          python setup.py install
          cd ..
          python -m PyInstaller main.py --onefile --hidden-import readchar
    - name: Create Archive
      uses: papeloto/action-zip@v1
      with:
          dest: ${{matrix.artifact_name}}
          files: dist/
    - name: Upload file
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{matrix.artifact_name}}
          asset_name: ${{format('{0}-{1}{2}',matrix.asset_name,env.GITHUB_REF_SLUG,matrix.suffix)}}
          tag: ${{github.ref}}
          overwrite: true
          body: "Release of simple pyInstaller binary, version ${{env.GITHUB_REF_SLUG}}"
